language: node_js 
node_js: stable

install: 
- npm install -g gulp 
- npm install

# - npm install -g gulp

script: 
- hexo clean
- hexo g

after_script: 
- cd ./public 
- git init 
- git config user.name "wrxiang"
- git config user.email "rxhome@163.com"
- git add . 
- git commit -m "Update docs with TRAVIS-CI."
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches: 
only: 
- resource 
env: 
global: 
- GH_REF: github.com/wrxiang/wrxiang.github.io.git 
