language: node_js # 设置语言
node_js: stable  #设置相应版本

cache:
    apt: true
    directories:
        - node_modules #缓存不经常更改的内容
        
before_install:
    - npm install hexo-cli -g
        
install: 
- npm install # 安装hexo及插件

script: 
- hexo clean #清除
- hexo g  #生成

after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/ 
- cd ./public 
- git config user.name "wrxiang"
- git config user.email "rxhome@163.com"
- git add . 
- git commit -m "Update docs with TRAVIS-CI."
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches: 
only: 
- resource 
env: 
global: 
- GH_REF: github.com/wrxiang/wrxiang.github.io.git #设置GH_REF
